# This workflow will build the extension jar and retain the artifact.
 # For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

 name: Build jar

 on: [workflow_dispatch]

 jobs:
   build_lnx:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt-hotspot'
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
     - name: Build with Gradle
       run: ./gradlew shadowjar -P toolchain=11
     - uses: actions/upload-artifact@v2
       with:
         name: linux-x86_64
         path: build/libs/*.jar
         retention-days: 1

   build_win:
     runs-on: windows-latest
     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt-hotspot'
     - name: Build with Gradle
       run: gradlew.bat shadowjar -P toolchain=11
       shell: cmd
     - uses: actions/upload-artifact@v2
       with:
         name: windows-x86_64
         path: build\\libs\\*.jar
         retention-days: 1

   build_mac:
     runs-on: macos-latest
     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt-hotspot'
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
     - name: Build with Gradle
       run: ./gradlew shadowjar -P toolchain=11
     - uses: actions/upload-artifact@v2
       with:
         name: macosx-x86_64
         path: build/libs/*.jar
         retention-days: 1
